apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "sw-hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 9393
      targetPort: 9393
      protocol: TCP
      name: metrics
  selector:
    {{- include "sw-hello-world.selectorLabels" . | nindent 4 }}
